services:

  # A Docker backend spring server service
  - type: web
    name: app-server
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: flowerknower-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: flowerknower-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: flowerknower-db
          property: password

# ------------------------------######-------------------------------------
  # A Docker frontend react service
  - type: web
    name: app-client
    env: docker
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    dockerContext: .

# ------------------------------######-------------------------------------
  # A Docker AI server fastAPI service
  - type: web
    name: ml-server
    env: docker
    rootDir: ml
    dockerfilePath: ./Dockerfile
    dockerContext: .


# ------------------------------######-------------------------------------
databases:
  - name: flowerknower-db
    databaseName: flowerknower # optional (Render may add a suffix)
    user: postgres # optional
    ipAllowList: [] # only allow internal connections
